#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Health.Applications.WalkMe
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wlkmi")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgroup(group instance);
    partial void Updategroup(group instance);
    partial void Deletegroup(group instance);
    partial void Insertgroup_user_assoc(group_user_assoc instance);
    partial void Updategroup_user_assoc(group_user_assoc instance);
    partial void Deletegroup_user_assoc(group_user_assoc instance);
    partial void Insertsync_setting(sync_setting instance);
    partial void Updatesync_setting(sync_setting instance);
    partial void Deletesync_setting(sync_setting instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertwalk_log(walk_log instance);
    partial void Updatewalk_log(walk_log instance);
    partial void Deletewalk_log(walk_log instance);
    partial void Insertwc_audit_log(wc_audit_log instance);
    partial void Updatewc_audit_log(wc_audit_log instance);
    partial void Deletewc_audit_log(wc_audit_log instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WalkMeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<group> groups
		{
			get
			{
				return this.GetTable<group>();
			}
		}
		
		public System.Data.Linq.Table<group_user_assoc> group_user_assocs
		{
			get
			{
				return this.GetTable<group_user_assoc>();
			}
		}
		
		public System.Data.Linq.Table<sync_setting> sync_settings
		{
			get
			{
				return this.GetTable<sync_setting>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<walk_log> walk_logs
		{
			get
			{
				return this.GetTable<walk_log>();
			}
		}
		
		public System.Data.Linq.Table<wc_audit_log> wc_audit_logs
		{
			get
			{
				return this.GetTable<wc_audit_log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[group]")]
	public partial class group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _group_id;
		
		private string _group_name;
		
		private string _group_description;
		
		private System.Nullable<int> _group_private;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
		private EntitySet<group_user_assoc> _group_user_assocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongroup_idChanging(int value);
    partial void Ongroup_idChanged();
    partial void Ongroup_nameChanging(string value);
    partial void Ongroup_nameChanged();
    partial void Ongroup_descriptionChanging(string value);
    partial void Ongroup_descriptionChanged();
    partial void Ongroup_privateChanging(System.Nullable<int> value);
    partial void Ongroup_privateChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public group()
		{
			this._group_user_assocs = new EntitySet<group_user_assoc>(new Action<group_user_assoc>(this.attach_group_user_assocs), new Action<group_user_assoc>(this.detach_group_user_assocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int group_id
		{
			get
			{
				return this._group_id;
			}
			set
			{
				if ((this._group_id != value))
				{
					this.Ongroup_idChanging(value);
					this.SendPropertyChanging();
					this._group_id = value;
					this.SendPropertyChanged("group_id");
					this.Ongroup_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string group_name
		{
			get
			{
				return this._group_name;
			}
			set
			{
				if ((this._group_name != value))
				{
					this.Ongroup_nameChanging(value);
					this.SendPropertyChanging();
					this._group_name = value;
					this.SendPropertyChanged("group_name");
					this.Ongroup_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_description", DbType="NVarChar(MAX)")]
		public string group_description
		{
			get
			{
				return this._group_description;
			}
			set
			{
				if ((this._group_description != value))
				{
					this.Ongroup_descriptionChanging(value);
					this.SendPropertyChanging();
					this._group_description = value;
					this.SendPropertyChanged("group_description");
					this.Ongroup_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_private", DbType="Int")]
		public System.Nullable<int> group_private
		{
			get
			{
				return this._group_private;
			}
			set
			{
				if ((this._group_private != value))
				{
					this.Ongroup_privateChanging(value);
					this.SendPropertyChanging();
					this._group_private = value;
					this.SendPropertyChanged("group_private");
					this.Ongroup_privateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="group_group_user_assoc", Storage="_group_user_assocs", ThisKey="group_id", OtherKey="group_id")]
		public EntitySet<group_user_assoc> group_user_assocs
		{
			get
			{
				return this._group_user_assocs;
			}
			set
			{
				this._group_user_assocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_group_user_assocs(group_user_assoc entity)
		{
			this.SendPropertyChanging();
			entity.group = this;
		}
		
		private void detach_group_user_assocs(group_user_assoc entity)
		{
			this.SendPropertyChanging();
			entity.group = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.group_user_assoc")]
	public partial class group_user_assoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _group_id;
		
		private int _user_id;
		
		private int _role;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
		private EntityRef<group> _group;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongroup_idChanging(int value);
    partial void Ongroup_idChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnroleChanging(int value);
    partial void OnroleChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public group_user_assoc()
		{
			this._group = default(EntityRef<group>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int group_id
		{
			get
			{
				return this._group_id;
			}
			set
			{
				if ((this._group_id != value))
				{
					if (this._group.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongroup_idChanging(value);
					this.SendPropertyChanging();
					this._group_id = value;
					this.SendPropertyChanged("group_id");
					this.Ongroup_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int NOT NULL")]
		public int role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="group_group_user_assoc", Storage="_group", ThisKey="group_id", OtherKey="group_id", IsForeignKey=true)]
		public group group
		{
			get
			{
				return this._group.Entity;
			}
			set
			{
				group previousValue = this._group.Entity;
				if (((previousValue != value) 
							|| (this._group.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._group.Entity = null;
						previousValue.group_user_assocs.Remove(this);
					}
					this._group.Entity = value;
					if ((value != null))
					{
						value.group_user_assocs.Add(this);
						this._group_id = value.group_id;
					}
					else
					{
						this._group_id = default(int);
					}
					this.SendPropertyChanged("group");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_group_user_assoc", Storage="_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.group_user_assocs.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.group_user_assocs.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sync_settings")]
	public partial class sync_setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sync_server_name;
		
		private int _sync_status;
		
		private System.DateTime _sync_timestamp;
		
		private int _sync_frequency_hours;
		
		private int _sync_id;
		
		private System.Guid _sync_job_id;
		
		private string _sync_msg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsync_server_nameChanging(string value);
    partial void Onsync_server_nameChanged();
    partial void Onsync_statusChanging(int value);
    partial void Onsync_statusChanged();
    partial void Onsync_timestampChanging(System.DateTime value);
    partial void Onsync_timestampChanged();
    partial void Onsync_frequency_hoursChanging(int value);
    partial void Onsync_frequency_hoursChanged();
    partial void Onsync_idChanging(int value);
    partial void Onsync_idChanged();
    partial void Onsync_job_idChanging(System.Guid value);
    partial void Onsync_job_idChanged();
    partial void Onsync_msgChanging(string value);
    partial void Onsync_msgChanged();
    #endregion
		
		public sync_setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_server_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sync_server_name
		{
			get
			{
				return this._sync_server_name;
			}
			set
			{
				if ((this._sync_server_name != value))
				{
					this.Onsync_server_nameChanging(value);
					this.SendPropertyChanging();
					this._sync_server_name = value;
					this.SendPropertyChanged("sync_server_name");
					this.Onsync_server_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_status", DbType="Int NOT NULL")]
		public int sync_status
		{
			get
			{
				return this._sync_status;
			}
			set
			{
				if ((this._sync_status != value))
				{
					this.Onsync_statusChanging(value);
					this.SendPropertyChanging();
					this._sync_status = value;
					this.SendPropertyChanged("sync_status");
					this.Onsync_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime sync_timestamp
		{
			get
			{
				return this._sync_timestamp;
			}
			set
			{
				if ((this._sync_timestamp != value))
				{
					this.Onsync_timestampChanging(value);
					this.SendPropertyChanging();
					this._sync_timestamp = value;
					this.SendPropertyChanged("sync_timestamp");
					this.Onsync_timestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_frequency_hours", DbType="Int NOT NULL")]
		public int sync_frequency_hours
		{
			get
			{
				return this._sync_frequency_hours;
			}
			set
			{
				if ((this._sync_frequency_hours != value))
				{
					this.Onsync_frequency_hoursChanging(value);
					this.SendPropertyChanging();
					this._sync_frequency_hours = value;
					this.SendPropertyChanged("sync_frequency_hours");
					this.Onsync_frequency_hoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sync_id
		{
			get
			{
				return this._sync_id;
			}
			set
			{
				if ((this._sync_id != value))
				{
					this.Onsync_idChanging(value);
					this.SendPropertyChanging();
					this._sync_id = value;
					this.SendPropertyChanged("sync_id");
					this.Onsync_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_job_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid sync_job_id
		{
			get
			{
				return this._sync_job_id;
			}
			set
			{
				if ((this._sync_job_id != value))
				{
					this.Onsync_job_idChanging(value);
					this.SendPropertyChanging();
					this._sync_job_id = value;
					this.SendPropertyChanged("sync_job_id");
					this.Onsync_job_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sync_msg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string sync_msg
		{
			get
			{
				return this._sync_msg;
			}
			set
			{
				if ((this._sync_msg != value))
				{
					this.Onsync_msgChanging(value);
					this.SendPropertyChanging();
					this._sync_msg = value;
					this.SendPropertyChanged("sync_msg");
					this.Onsync_msgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_email;
		
		private string _user_nickname;
		
		private int _user_zip;
		
		private int _user_birthyear;
		
		private string _user_groups;
		
		private int _user_stride;
		
		private int _user_weight;
		
		private System.Guid _hv_recordid;
		
		private System.Nullable<System.DateTime> _user_last_login;
		
		private string _user_last_client_ip;
		
		private System.Nullable<long> _user_total_steps;
		
		private System.Nullable<double> _user_total_distance;
		
		private System.Nullable<int> _user_weekly_steps;
		
		private System.Nullable<double> _user_weekly_distance;
		
		private System.Nullable<double> _user_weekly_calories;
		
		private System.Nullable<long> _user_monthly_steps;
		
		private System.Nullable<long> _user_annual_steps;
		
		private System.Guid _hv_personid;
		
		private int _user_sharing_flag;
		
		private System.Nullable<System.DateTime> _hv_last_sync_time;
		
		private System.Nullable<int> _daily_goal_steps;
		
		private System.Nullable<double> _daily_goal_calories;
		
		private System.Nullable<int> _daily_goal_aerobic_steps;
		
		private System.Nullable<double> _daily_goal_distance;
		
		private int _user_height;
		
		private int _user_reg_complete_flag;
		
		private System.DateTime _updated_at;
		
		private System.DateTime _created_at;
		
		private string _hv_sync_entity_name;
		
		private int _hv_sync_status;
		
		private EntitySet<group_user_assoc> _group_user_assocs;
		
		private EntitySet<walk_log> _walk_logs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_nicknameChanging(string value);
    partial void Onuser_nicknameChanged();
    partial void Onuser_zipChanging(int value);
    partial void Onuser_zipChanged();
    partial void Onuser_birthyearChanging(int value);
    partial void Onuser_birthyearChanged();
    partial void Onuser_groupsChanging(string value);
    partial void Onuser_groupsChanged();
    partial void Onuser_strideChanging(int value);
    partial void Onuser_strideChanged();
    partial void Onuser_weightChanging(int value);
    partial void Onuser_weightChanged();
    partial void Onhv_recordidChanging(System.Guid value);
    partial void Onhv_recordidChanged();
    partial void Onuser_last_loginChanging(System.Nullable<System.DateTime> value);
    partial void Onuser_last_loginChanged();
    partial void Onuser_last_client_ipChanging(string value);
    partial void Onuser_last_client_ipChanged();
    partial void Onuser_total_stepsChanging(System.Nullable<long> value);
    partial void Onuser_total_stepsChanged();
    partial void Onuser_total_distanceChanging(System.Nullable<double> value);
    partial void Onuser_total_distanceChanged();
    partial void Onuser_weekly_stepsChanging(System.Nullable<int> value);
    partial void Onuser_weekly_stepsChanged();
    partial void Onuser_weekly_distanceChanging(System.Nullable<double> value);
    partial void Onuser_weekly_distanceChanged();
    partial void Onuser_weekly_caloriesChanging(System.Nullable<double> value);
    partial void Onuser_weekly_caloriesChanged();
    partial void Onuser_monthly_stepsChanging(System.Nullable<long> value);
    partial void Onuser_monthly_stepsChanged();
    partial void Onuser_annual_stepsChanging(System.Nullable<long> value);
    partial void Onuser_annual_stepsChanged();
    partial void Onhv_personidChanging(System.Guid value);
    partial void Onhv_personidChanged();
    partial void Onuser_sharing_flagChanging(int value);
    partial void Onuser_sharing_flagChanged();
    partial void Onhv_last_sync_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onhv_last_sync_timeChanged();
    partial void Ondaily_goal_stepsChanging(System.Nullable<int> value);
    partial void Ondaily_goal_stepsChanged();
    partial void Ondaily_goal_caloriesChanging(System.Nullable<double> value);
    partial void Ondaily_goal_caloriesChanged();
    partial void Ondaily_goal_aerobic_stepsChanging(System.Nullable<int> value);
    partial void Ondaily_goal_aerobic_stepsChanged();
    partial void Ondaily_goal_distanceChanging(System.Nullable<double> value);
    partial void Ondaily_goal_distanceChanged();
    partial void Onuser_heightChanging(int value);
    partial void Onuser_heightChanged();
    partial void Onuser_reg_complete_flagChanging(int value);
    partial void Onuser_reg_complete_flagChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onhv_sync_entity_nameChanging(string value);
    partial void Onhv_sync_entity_nameChanged();
    partial void Onhv_sync_statusChanging(int value);
    partial void Onhv_sync_statusChanged();
    #endregion
		
		public user()
		{
			this._group_user_assocs = new EntitySet<group_user_assoc>(new Action<group_user_assoc>(this.attach_group_user_assocs), new Action<group_user_assoc>(this.detach_group_user_assocs));
			this._walk_logs = new EntitySet<walk_log>(new Action<walk_log>(this.attach_walk_logs), new Action<walk_log>(this.detach_walk_logs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="NVarChar(100)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_nickname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_nickname
		{
			get
			{
				return this._user_nickname;
			}
			set
			{
				if ((this._user_nickname != value))
				{
					this.Onuser_nicknameChanging(value);
					this.SendPropertyChanging();
					this._user_nickname = value;
					this.SendPropertyChanged("user_nickname");
					this.Onuser_nicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_zip", DbType="Int NOT NULL")]
		public int user_zip
		{
			get
			{
				return this._user_zip;
			}
			set
			{
				if ((this._user_zip != value))
				{
					this.Onuser_zipChanging(value);
					this.SendPropertyChanging();
					this._user_zip = value;
					this.SendPropertyChanged("user_zip");
					this.Onuser_zipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_birthyear", DbType="Int NOT NULL")]
		public int user_birthyear
		{
			get
			{
				return this._user_birthyear;
			}
			set
			{
				if ((this._user_birthyear != value))
				{
					this.Onuser_birthyearChanging(value);
					this.SendPropertyChanging();
					this._user_birthyear = value;
					this.SendPropertyChanged("user_birthyear");
					this.Onuser_birthyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_groups", DbType="NVarChar(1000)")]
		public string user_groups
		{
			get
			{
				return this._user_groups;
			}
			set
			{
				if ((this._user_groups != value))
				{
					this.Onuser_groupsChanging(value);
					this.SendPropertyChanging();
					this._user_groups = value;
					this.SendPropertyChanged("user_groups");
					this.Onuser_groupsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_stride", DbType="Int NOT NULL")]
		public int user_stride
		{
			get
			{
				return this._user_stride;
			}
			set
			{
				if ((this._user_stride != value))
				{
					this.Onuser_strideChanging(value);
					this.SendPropertyChanging();
					this._user_stride = value;
					this.SendPropertyChanged("user_stride");
					this.Onuser_strideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_weight", DbType="Int NOT NULL")]
		public int user_weight
		{
			get
			{
				return this._user_weight;
			}
			set
			{
				if ((this._user_weight != value))
				{
					this.Onuser_weightChanging(value);
					this.SendPropertyChanging();
					this._user_weight = value;
					this.SendPropertyChanged("user_weight");
					this.Onuser_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hv_recordid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid hv_recordid
		{
			get
			{
				return this._hv_recordid;
			}
			set
			{
				if ((this._hv_recordid != value))
				{
					this.Onhv_recordidChanging(value);
					this.SendPropertyChanging();
					this._hv_recordid = value;
					this.SendPropertyChanged("hv_recordid");
					this.Onhv_recordidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_last_login", DbType="DateTime")]
		public System.Nullable<System.DateTime> user_last_login
		{
			get
			{
				return this._user_last_login;
			}
			set
			{
				if ((this._user_last_login != value))
				{
					this.Onuser_last_loginChanging(value);
					this.SendPropertyChanging();
					this._user_last_login = value;
					this.SendPropertyChanged("user_last_login");
					this.Onuser_last_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_last_client_ip", DbType="NVarChar(32)")]
		public string user_last_client_ip
		{
			get
			{
				return this._user_last_client_ip;
			}
			set
			{
				if ((this._user_last_client_ip != value))
				{
					this.Onuser_last_client_ipChanging(value);
					this.SendPropertyChanging();
					this._user_last_client_ip = value;
					this.SendPropertyChanged("user_last_client_ip");
					this.Onuser_last_client_ipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_total_steps", DbType="BigInt")]
		public System.Nullable<long> user_total_steps
		{
			get
			{
				return this._user_total_steps;
			}
			set
			{
				if ((this._user_total_steps != value))
				{
					this.Onuser_total_stepsChanging(value);
					this.SendPropertyChanging();
					this._user_total_steps = value;
					this.SendPropertyChanged("user_total_steps");
					this.Onuser_total_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_total_distance", DbType="Float")]
		public System.Nullable<double> user_total_distance
		{
			get
			{
				return this._user_total_distance;
			}
			set
			{
				if ((this._user_total_distance != value))
				{
					this.Onuser_total_distanceChanging(value);
					this.SendPropertyChanging();
					this._user_total_distance = value;
					this.SendPropertyChanged("user_total_distance");
					this.Onuser_total_distanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_weekly_steps", DbType="Int")]
		public System.Nullable<int> user_weekly_steps
		{
			get
			{
				return this._user_weekly_steps;
			}
			set
			{
				if ((this._user_weekly_steps != value))
				{
					this.Onuser_weekly_stepsChanging(value);
					this.SendPropertyChanging();
					this._user_weekly_steps = value;
					this.SendPropertyChanged("user_weekly_steps");
					this.Onuser_weekly_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_weekly_distance", DbType="Float")]
		public System.Nullable<double> user_weekly_distance
		{
			get
			{
				return this._user_weekly_distance;
			}
			set
			{
				if ((this._user_weekly_distance != value))
				{
					this.Onuser_weekly_distanceChanging(value);
					this.SendPropertyChanging();
					this._user_weekly_distance = value;
					this.SendPropertyChanged("user_weekly_distance");
					this.Onuser_weekly_distanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_weekly_calories", DbType="Float")]
		public System.Nullable<double> user_weekly_calories
		{
			get
			{
				return this._user_weekly_calories;
			}
			set
			{
				if ((this._user_weekly_calories != value))
				{
					this.Onuser_weekly_caloriesChanging(value);
					this.SendPropertyChanging();
					this._user_weekly_calories = value;
					this.SendPropertyChanged("user_weekly_calories");
					this.Onuser_weekly_caloriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_monthly_steps", DbType="BigInt")]
		public System.Nullable<long> user_monthly_steps
		{
			get
			{
				return this._user_monthly_steps;
			}
			set
			{
				if ((this._user_monthly_steps != value))
				{
					this.Onuser_monthly_stepsChanging(value);
					this.SendPropertyChanging();
					this._user_monthly_steps = value;
					this.SendPropertyChanged("user_monthly_steps");
					this.Onuser_monthly_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_annual_steps", DbType="BigInt")]
		public System.Nullable<long> user_annual_steps
		{
			get
			{
				return this._user_annual_steps;
			}
			set
			{
				if ((this._user_annual_steps != value))
				{
					this.Onuser_annual_stepsChanging(value);
					this.SendPropertyChanging();
					this._user_annual_steps = value;
					this.SendPropertyChanged("user_annual_steps");
					this.Onuser_annual_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hv_personid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid hv_personid
		{
			get
			{
				return this._hv_personid;
			}
			set
			{
				if ((this._hv_personid != value))
				{
					this.Onhv_personidChanging(value);
					this.SendPropertyChanging();
					this._hv_personid = value;
					this.SendPropertyChanged("hv_personid");
					this.Onhv_personidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_sharing_flag", DbType="Int NOT NULL")]
		public int user_sharing_flag
		{
			get
			{
				return this._user_sharing_flag;
			}
			set
			{
				if ((this._user_sharing_flag != value))
				{
					this.Onuser_sharing_flagChanging(value);
					this.SendPropertyChanging();
					this._user_sharing_flag = value;
					this.SendPropertyChanged("user_sharing_flag");
					this.Onuser_sharing_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hv_last_sync_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> hv_last_sync_time
		{
			get
			{
				return this._hv_last_sync_time;
			}
			set
			{
				if ((this._hv_last_sync_time != value))
				{
					this.Onhv_last_sync_timeChanging(value);
					this.SendPropertyChanging();
					this._hv_last_sync_time = value;
					this.SendPropertyChanged("hv_last_sync_time");
					this.Onhv_last_sync_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_goal_steps", DbType="Int")]
		public System.Nullable<int> daily_goal_steps
		{
			get
			{
				return this._daily_goal_steps;
			}
			set
			{
				if ((this._daily_goal_steps != value))
				{
					this.Ondaily_goal_stepsChanging(value);
					this.SendPropertyChanging();
					this._daily_goal_steps = value;
					this.SendPropertyChanged("daily_goal_steps");
					this.Ondaily_goal_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_goal_calories", DbType="Float")]
		public System.Nullable<double> daily_goal_calories
		{
			get
			{
				return this._daily_goal_calories;
			}
			set
			{
				if ((this._daily_goal_calories != value))
				{
					this.Ondaily_goal_caloriesChanging(value);
					this.SendPropertyChanging();
					this._daily_goal_calories = value;
					this.SendPropertyChanged("daily_goal_calories");
					this.Ondaily_goal_caloriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_goal_aerobic_steps", DbType="Int")]
		public System.Nullable<int> daily_goal_aerobic_steps
		{
			get
			{
				return this._daily_goal_aerobic_steps;
			}
			set
			{
				if ((this._daily_goal_aerobic_steps != value))
				{
					this.Ondaily_goal_aerobic_stepsChanging(value);
					this.SendPropertyChanging();
					this._daily_goal_aerobic_steps = value;
					this.SendPropertyChanged("daily_goal_aerobic_steps");
					this.Ondaily_goal_aerobic_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daily_goal_distance", DbType="Float")]
		public System.Nullable<double> daily_goal_distance
		{
			get
			{
				return this._daily_goal_distance;
			}
			set
			{
				if ((this._daily_goal_distance != value))
				{
					this.Ondaily_goal_distanceChanging(value);
					this.SendPropertyChanging();
					this._daily_goal_distance = value;
					this.SendPropertyChanged("daily_goal_distance");
					this.Ondaily_goal_distanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_height", DbType="Int NOT NULL")]
		public int user_height
		{
			get
			{
				return this._user_height;
			}
			set
			{
				if ((this._user_height != value))
				{
					this.Onuser_heightChanging(value);
					this.SendPropertyChanging();
					this._user_height = value;
					this.SendPropertyChanged("user_height");
					this.Onuser_heightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_reg_complete_flag", DbType="Int NOT NULL")]
		public int user_reg_complete_flag
		{
			get
			{
				return this._user_reg_complete_flag;
			}
			set
			{
				if ((this._user_reg_complete_flag != value))
				{
					this.Onuser_reg_complete_flagChanging(value);
					this.SendPropertyChanging();
					this._user_reg_complete_flag = value;
					this.SendPropertyChanged("user_reg_complete_flag");
					this.Onuser_reg_complete_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hv_sync_entity_name", DbType="NVarChar(100)")]
		public string hv_sync_entity_name
		{
			get
			{
				return this._hv_sync_entity_name;
			}
			set
			{
				if ((this._hv_sync_entity_name != value))
				{
					this.Onhv_sync_entity_nameChanging(value);
					this.SendPropertyChanging();
					this._hv_sync_entity_name = value;
					this.SendPropertyChanged("hv_sync_entity_name");
					this.Onhv_sync_entity_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hv_sync_status", DbType="Int NOT NULL")]
		public int hv_sync_status
		{
			get
			{
				return this._hv_sync_status;
			}
			set
			{
				if ((this._hv_sync_status != value))
				{
					this.Onhv_sync_statusChanging(value);
					this.SendPropertyChanging();
					this._hv_sync_status = value;
					this.SendPropertyChanged("hv_sync_status");
					this.Onhv_sync_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_group_user_assoc", Storage="_group_user_assocs", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<group_user_assoc> group_user_assocs
		{
			get
			{
				return this._group_user_assocs;
			}
			set
			{
				this._group_user_assocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_walk_log", Storage="_walk_logs", ThisKey="user_id", OtherKey="log_user")]
		public EntitySet<walk_log> walk_logs
		{
			get
			{
				return this._walk_logs;
			}
			set
			{
				this._walk_logs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_group_user_assocs(group_user_assoc entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_group_user_assocs(group_user_assoc entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_walk_logs(walk_log entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_walk_logs(walk_log entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.walk_log")]
	public partial class walk_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _log_id;
		
		private System.Nullable<long> _log_steps;
		
		private System.Nullable<long> _log_aerobicsteps;
		
		private string _log_step_hourly_samples;
		
		private string _log_aerobic_hourly_samples;
		
		private System.Nullable<double> _log_calories;
		
		private System.Nullable<double> _log_distance;
		
		private System.Nullable<int> _log_weight;
		
		private System.DateTime _log_date;
		
		private int _log_user;
		
		private System.DateTime _updated_at;
		
		private System.Guid _hv_item_id;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(long value);
    partial void Onlog_idChanged();
    partial void Onlog_stepsChanging(System.Nullable<long> value);
    partial void Onlog_stepsChanged();
    partial void Onlog_aerobicstepsChanging(System.Nullable<long> value);
    partial void Onlog_aerobicstepsChanged();
    partial void Onlog_step_hourly_samplesChanging(string value);
    partial void Onlog_step_hourly_samplesChanged();
    partial void Onlog_aerobic_hourly_samplesChanging(string value);
    partial void Onlog_aerobic_hourly_samplesChanged();
    partial void Onlog_caloriesChanging(System.Nullable<double> value);
    partial void Onlog_caloriesChanged();
    partial void Onlog_distanceChanging(System.Nullable<double> value);
    partial void Onlog_distanceChanged();
    partial void Onlog_weightChanging(System.Nullable<int> value);
    partial void Onlog_weightChanged();
    partial void Onlog_dateChanging(System.DateTime value);
    partial void Onlog_dateChanged();
    partial void Onlog_userChanging(int value);
    partial void Onlog_userChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    partial void Onhv_item_idChanging(System.Guid value);
    partial void Onhv_item_idChanged();
    #endregion
		
		public walk_log()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_steps", DbType="BigInt")]
		public System.Nullable<long> log_steps
		{
			get
			{
				return this._log_steps;
			}
			set
			{
				if ((this._log_steps != value))
				{
					this.Onlog_stepsChanging(value);
					this.SendPropertyChanging();
					this._log_steps = value;
					this.SendPropertyChanged("log_steps");
					this.Onlog_stepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_aerobicsteps", DbType="BigInt")]
		public System.Nullable<long> log_aerobicsteps
		{
			get
			{
				return this._log_aerobicsteps;
			}
			set
			{
				if ((this._log_aerobicsteps != value))
				{
					this.Onlog_aerobicstepsChanging(value);
					this.SendPropertyChanging();
					this._log_aerobicsteps = value;
					this.SendPropertyChanged("log_aerobicsteps");
					this.Onlog_aerobicstepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_step_hourly_samples", DbType="NVarChar(300)")]
		public string log_step_hourly_samples
		{
			get
			{
				return this._log_step_hourly_samples;
			}
			set
			{
				if ((this._log_step_hourly_samples != value))
				{
					this.Onlog_step_hourly_samplesChanging(value);
					this.SendPropertyChanging();
					this._log_step_hourly_samples = value;
					this.SendPropertyChanged("log_step_hourly_samples");
					this.Onlog_step_hourly_samplesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_aerobic_hourly_samples", DbType="NVarChar(300)")]
		public string log_aerobic_hourly_samples
		{
			get
			{
				return this._log_aerobic_hourly_samples;
			}
			set
			{
				if ((this._log_aerobic_hourly_samples != value))
				{
					this.Onlog_aerobic_hourly_samplesChanging(value);
					this.SendPropertyChanging();
					this._log_aerobic_hourly_samples = value;
					this.SendPropertyChanged("log_aerobic_hourly_samples");
					this.Onlog_aerobic_hourly_samplesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_calories", DbType="Float")]
		public System.Nullable<double> log_calories
		{
			get
			{
				return this._log_calories;
			}
			set
			{
				if ((this._log_calories != value))
				{
					this.Onlog_caloriesChanging(value);
					this.SendPropertyChanging();
					this._log_calories = value;
					this.SendPropertyChanged("log_calories");
					this.Onlog_caloriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_distance", DbType="Float")]
		public System.Nullable<double> log_distance
		{
			get
			{
				return this._log_distance;
			}
			set
			{
				if ((this._log_distance != value))
				{
					this.Onlog_distanceChanging(value);
					this.SendPropertyChanging();
					this._log_distance = value;
					this.SendPropertyChanged("log_distance");
					this.Onlog_distanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_weight", DbType="Int")]
		public System.Nullable<int> log_weight
		{
			get
			{
				return this._log_weight;
			}
			set
			{
				if ((this._log_weight != value))
				{
					this.Onlog_weightChanging(value);
					this.SendPropertyChanging();
					this._log_weight = value;
					this.SendPropertyChanged("log_weight");
					this.Onlog_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_date", DbType="DateTime NOT NULL")]
		public System.DateTime log_date
		{
			get
			{
				return this._log_date;
			}
			set
			{
				if ((this._log_date != value))
				{
					this.Onlog_dateChanging(value);
					this.SendPropertyChanging();
					this._log_date = value;
					this.SendPropertyChanged("log_date");
					this.Onlog_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_user", DbType="Int NOT NULL")]
		public int log_user
		{
			get
			{
				return this._log_user;
			}
			set
			{
				if ((this._log_user != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlog_userChanging(value);
					this.SendPropertyChanging();
					this._log_user = value;
					this.SendPropertyChanged("log_user");
					this.Onlog_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hv_item_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid hv_item_id
		{
			get
			{
				return this._hv_item_id;
			}
			set
			{
				if ((this._hv_item_id != value))
				{
					this.Onhv_item_idChanging(value);
					this.SendPropertyChanging();
					this._hv_item_id = value;
					this.SendPropertyChanged("hv_item_id");
					this.Onhv_item_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_walk_log", Storage="_user", ThisKey="log_user", OtherKey="user_id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.walk_logs.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.walk_logs.Add(this);
						this._log_user = value.user_id;
					}
					else
					{
						this._log_user = default(int);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wc_audit_log")]
	public partial class wc_audit_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _log_id;
		
		private string _application_name;
		
		private string _server_name;
		
		private string _executing_entity;
		
		private int _event_id;
		
		private int _event_severity;
		
		private System.DateTime _event_time;
		
		private string _event_message;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void Onapplication_nameChanging(string value);
    partial void Onapplication_nameChanged();
    partial void Onserver_nameChanging(string value);
    partial void Onserver_nameChanged();
    partial void Onexecuting_entityChanging(string value);
    partial void Onexecuting_entityChanged();
    partial void Onevent_idChanging(int value);
    partial void Onevent_idChanged();
    partial void Onevent_severityChanging(int value);
    partial void Onevent_severityChanged();
    partial void Onevent_timeChanging(System.DateTime value);
    partial void Onevent_timeChanged();
    partial void Onevent_messageChanging(string value);
    partial void Onevent_messageChanged();
    #endregion
		
		public wc_audit_log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string application_name
		{
			get
			{
				return this._application_name;
			}
			set
			{
				if ((this._application_name != value))
				{
					this.Onapplication_nameChanging(value);
					this.SendPropertyChanging();
					this._application_name = value;
					this.SendPropertyChanged("application_name");
					this.Onapplication_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_server_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string server_name
		{
			get
			{
				return this._server_name;
			}
			set
			{
				if ((this._server_name != value))
				{
					this.Onserver_nameChanging(value);
					this.SendPropertyChanging();
					this._server_name = value;
					this.SendPropertyChanged("server_name");
					this.Onserver_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_executing_entity", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string executing_entity
		{
			get
			{
				return this._executing_entity;
			}
			set
			{
				if ((this._executing_entity != value))
				{
					this.Onexecuting_entityChanging(value);
					this.SendPropertyChanging();
					this._executing_entity = value;
					this.SendPropertyChanged("executing_entity");
					this.Onexecuting_entityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="Int NOT NULL")]
		public int event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_severity", DbType="Int NOT NULL")]
		public int event_severity
		{
			get
			{
				return this._event_severity;
			}
			set
			{
				if ((this._event_severity != value))
				{
					this.Onevent_severityChanging(value);
					this.SendPropertyChanging();
					this._event_severity = value;
					this.SendPropertyChanged("event_severity");
					this.Onevent_severityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_time", DbType="DateTime NOT NULL")]
		public System.DateTime event_time
		{
			get
			{
				return this._event_time;
			}
			set
			{
				if ((this._event_time != value))
				{
					this.Onevent_timeChanging(value);
					this.SendPropertyChanging();
					this._event_time = value;
					this.SendPropertyChanged("event_time");
					this.Onevent_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_message", DbType="NVarChar(MAX)")]
		public string event_message
		{
			get
			{
				return this._event_message;
			}
			set
			{
				if ((this._event_message != value))
				{
					this.Onevent_messageChanging(value);
					this.SendPropertyChanging();
					this._event_message = value;
					this.SendPropertyChanged("event_message");
					this.Onevent_messageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
